### ISSUE TITLE
Browserify All The Things

### ISSUE THREAD

**Issue by bevacqua** [nodeconf/london#2]
This talk covers how to use `browserify` to develop front-end modular code using Common.JS, and how you can write tests for browserified code using `tape`. I'll also talk about Testling, explaining how to run these tests in the cloud or locally. I'll also explain how to create packages that work well in both Node and the client, demonstrating with a few different packages that I've written lately such as [taunus](https://github.com/bevacqua/taunus), [ponymark](https://github.com/bevacqua/ponymark), and [contra](https://github.com/bevacqua/contra).

**Comment by mikeal** [comment]
Browserify is awesome :) 

I'd like to know what the story is going to be? Are you going to walk through building something?

It's important to have semi-narrative structure in order to keep the talk within 20 minutes because it helps you cut things that don't fall into the narrative :)

**Comment by bevacqua** [comment]
Yeah, so, specifically I wanted to describe how Browserify enables you to:
- bring modularity into the browser, yada-yada-yada
- use all of `npm`, which is _huge_ and the fastest growing pm out there
- share code between the browser and the server in a way that makes sense (e.g switching out implementation details)

Walking through how I built one of those projects and using that to explain those points could definitely be a way to do it.

**Comment by mikeal** [comment]
I'd like to accept this talk but before I do I'd like to mention that we don't have the budget to fly anyone in from outside of Europe.

**Comment by bevacqua** [comment]
Ah, I kind of expected that -- it being a single day conf and all. Anyways, thought I'd give it one shot!

Loved JSFest in SF, you're good at organizing stuff. Keep it up

**Comment by orliesaurus** [comment]
@bevacqua  happy to present for you and have a tshirt with your face on stage

**Comment by mikeal** [comment]
@bevacqua ya, if you know of anyone locally that could handle this talk i'd be happy to have them do it :)
