### ISSUE TITLE
Anyone have the font handy for the logo?

### ISSUE THREAD

**Issue by dcbartlett** [nodeconf/london#28]
i need that scratched up font that was used in the logo if anyone has the name/font file handy.

**Comment by dcbartlett** [comment]
:bump:

**Comment by iancrowther** [comment]
@dcbartlett - is this still an issue?

**Comment by fintanr** [comment]
Let me check what we ended up with for OneShot

**Comment by fintanr** [comment]
The fonts were apparently 'Avenir' and 'Capture-It'

**Comment by iancrowther** [comment]
thanks @fintanr :+1:

**Comment by dcbartlett** [comment]
THANKS!!
