### ISSUE TITLE
Great British Flying Node Circus

### ISSUE THREAD

**Issue by olizilla** [nodeconf/london#29]
Dear @mikeal 

We'd like to run a super fun NodeConf for London in 2016.

![flying-circus](https://cloud.githubusercontent.com/assets/58871/8677411/cbb11e1c-2a46-11e5-87ba-6a7e33a9ccef.gif)

Please may we? 

Yours,

@olizilla & @iancrowther

**Comment by iancrowther** [comment]
Most certainly a +1

**Comment by fforres** [comment]
I love the idea :+1:
