### ISSUE TITLE
Set a date for NodeConf London

### ISSUE THREAD

**Issue by iancrowther** [nodeconf/london#31]

**Comment by iancrowther** [comment]
We need a landing page with the date.

we don't know the venue yet as we have no idea of demand.

**Comment by mikeal** [comment]
If you don't have a venue I wouldn't commit to a date yet, maybe just commit to a month :)

**Comment by iancrowther** [comment]
Makes sense

May 2016

**Comment by mikeal** [comment]
Should we rename this repo to "london-2014" and create a new "london" repo for 2015?

**Comment by iancrowther** [comment]
sure.  we had planned to do the next conf in 2016 as the calendar is looking pretty congested now.

Also we want time to do the detail

**Comment by iancrowther** [comment]
I don't want this event to be and feel rushed, its damaging to the NodeConf brand

**Comment by mikeal** [comment]
Some of my favorite events were the ones I did rather quickly. That said, May is a busy month which usually has JSConf US in it.

**Comment by iancrowther** [comment]
I am conducting some research into London conferences to avoid clash, do you have a similar list for the US e.g the main players.

@voodootikigod - can you help here at all?

**Comment by mikeal** [comment]
We’ve attempted to maintain them in the past but never had as accurate a picture as http://lanyrd.com/topics/javascript/ http://lanyrd.com/topics/javascript/

Although depending on the month you may just want to ask a few organizers that have been doing events in that month for a while, best way to do that is to go backwards in lanyrd to see old events in that month.

-Mikeal
