### ISSUE TITLE
Permission?

### ISSUE THREAD

**Issue by iancrowther** [nodeconf/london#35]
@mikeal can i get admin on this repo pls :-)

**Comment by mikeal** [comment]
Wow, this repo pre-dated the whole teams system :) Added a London team and invited you, ping me one you accept so that i can make you the mean manager.

**Comment by iancrowther** [comment]
have accepted - no merge still

**Comment by mikeal** [comment]
Fixed, the team is Admin now and you're a team maintainer :)

**Comment by iancrowther** [comment]
all systems green. thanks for the prompt response.
