### ISSUE TITLE
Help contacting v8

### ISSUE THREAD

**Issue by iancrowther** [nodeconf/london#44]
Hi,

I would love to get either the Google Cloud Platform team or the V8 team to speak at NodeConf London but need some help contacting the right people.

Can anyone help?

cc' @targos @bnoordhuis @indutny @ofrobots @trevnorris @mikeal @maxogden

the cfp closes shortly and can be found at http://london.nodeconf.com/call-for-speakers

**Comment by bnoordhuis** [comment]
@hashseed Would you or someone from your team want to speak?

**Comment by hashseed** [comment]
I sent out a mail to the internal mailing list to see whether anyone is interested. I'll keep you updated.

**Comment by iancrowther** [comment]
that's fantastic, thank you.

my email is ian.crowther@nearform.com if anyone has questions

**Comment by hashseed** [comment]
Is there any chance the deadline can be extended? Currently a bunch of team members, including some based in London, are on vacation.

**Comment by iancrowther** [comment]
drop me an email and we can discuss, I'll tell you my goals and then we can explore.
