### ISSUE TITLE
Building 100% silo free realtime applications...

### ISSUE THREAD

**Issue by lloydwatkin** [nodeconf/london#5]
You've played with realtime, lets do it properly...

♬ First I was afraid, I was petrified ♬
Kept thinking I could never live without realtime interaction client-side.
♪ But then I spent so many nights thinking how XML did me wrong. ♫
And I grew strong, and JSON helped me get along ♩
♩ And so you’re back with no name-space ♫
♫ I just walked in to find no silos here ‘cause its all de-cen-tral-ized
I shouldn’t used that custom format
XMPP and JSON is the key ♪
♬ If I’d known for just one second interoperability wouldn’t bother me... ♬

This talk breaks out of the silos and shows you how to build real time federated 100% silo-free services using javascript and the XMPP messaging network. Includes 100% more DISCO.

**Comment by mikeal** [comment]
This talk is accepted, can you give me a reduced one paragraph summary for the website :)

**Comment by lloydwatkin** [comment]
Cool, glad to hear it, will get a summary to you ASAP.

Just wondering if there's budget to cover travel/accommodation? Or a preferred conference hotel? As I'm away for the week before the event so I'd like to get things organised soon. Thanks.

**Comment by mikeal** [comment]
We have a limited budget for speaker travel and accommodations, so we can help with travel from within Europe. I'll check with the other organizers about a preferred hotel.

**Comment by lloydwatkin** [comment]
@mikeal actually, I'm happy with what you have written:

  This talk breaks out of the silos and shows you how to build real time federated 100% silo-free services using javascript and the XMPP messaging network. Includes 100% more DISCO.

Or do you want MOAR paragraph for the website?

**Comment by mikeal** [comment]
can you email mikeal dot rogers at gmail so i can get you registered :)
