### ISSUE TITLE
Chat Robots Next Level Tooling

### ISSUE THREAD

**Issue by OleMchls** [nodeconf/london#6]
**Developers are lazy!** So we are great in creating tooling for our daily work. But it has its weaknesses, we are creating a tons of scripts on our local maschine, sometimes we share them via git or other vcs systems. But all over all this tooling sucks when it comes to collaboration. We developers also love hanging out in chat rooms like campfire or jabber.

Why not combine this via chat robots. Our tooling would be available to everyone without installing wired shell scripts plus we can get rid if questions like: `“Do you have the deploy lock?”` or `“Did you already migrate the database?”` - it’s all documented in the transcripts.

I’d like to talk about how to improve your daily work with [hubot](http://hubot.github.com/), a chat robot build by the fine folks at github.

**Comment by mikeal** [comment]
This talk is accepted. Can you give me a reduced one paragraph summary for the website.

**Comment by OleMchls** [comment]
Sure!

&lt;p&gt;
**Developers are lazy!** So we are great in creating tooling for our daily work. But it has its weaknesses, we are creating a tons of scripts on our local maschine, sometimes we share them via git or other vcs systems. But all over all this tooling sucks when it comes to collaboration. We developers also love hanging out in chat rooms like campfire or jabber.

Why not combine this via chat robots. Our tooling would be available to everyone without installing wired shell scripts plus we can get rid if questions like: `“Do you have the deploy lock?”` or `“Did you already migrate the database?”` - it’s all documented in the transcripts.

I’d like to talk about how to improve your daily work with [hubot](http://hubot.github.com/), a chat robot build by the fine folks at github.
&lt;/p&gt;

Ahhh, SCNR :wink: 

So here's how I would summarize this:

> Chat robots makes your live easier. Not only yours, it even makes your team collaborate better. _Yeah, sure._ That's a lot of brilliant claims, so lets check what this chat robots buzz is about. And how you and your team can profit from your own little, cool, chat robot!

Cool?

**Comment by mikeal** [comment]
can you email mikeal dot rogers at gmail so i can get you registered :)
