### ISSUE TITLE
How we build offline data sync for LoopBack

### ISSUE THREAD

**Issue by bajtos** [nodeconf/london#8]
As more and more users are primarily using their mobile devices to access the web, it’s becoming very important for the web apps to provide good experience even when the device is not connected. The common solution is to store data in a browser local storage and synchronize them with the server when there is network access available.

In  this talk, I’d like to tell the story of how we added support for offline data access to LoopBack, and explain the technology that makes this possible. A spoiler: we use browserify to run the same model code both on the server and in the browser, so users of the LoopBack framework don't have to do a lot of work to support offline sync for the models they define. There's more to it of course, which will be outlined in great detail during the talk.

LoopBack is a backend framework built specifically for servicing mobile clients, making it easy to  connect your mobile app all the way through to heterogeneous data sources like SQL, NoSQL or even SOAP services. 

Note that this talk isn't going to be a sales pitch. Although it's good for us to draw some attention to LoopBack, I'm mostly interested in discussing the underlying technology.

**Comment by mikeal** [comment]
This talk is accepted. Can you get me a reduced one paragraph summary for the website :)

**Comment by mikeal** [comment]
can you email mikeal dot rogers at gmail so i can get you registered :)
